import type { NextPage } from 'next'
import Head from 'next/head'
import TheHeader from '../components/TheHeader'
import News from '../components/News'
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>ИТМО | Новости</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <TheHeader/>
       <News/>
    </div>
  )
}

export default Home
